"use strict";

(function () {
  // Flip to true and reload the extension to surface [wh-farble:dw]
  // diagnostics in the page console. Off by default — these fire at
  // document_start on every navigation and would be noisy in real use.
  var DEBUG = false;

  var MSG_TYPE = "__wearewatched__";
  var counts = {};
  // byScript: { 'google-analytics.com': { fingerprint: 4, permission: 0 }, ... }
  // Populated from inject.js's stack-walked caller host so background.js
  // can resolve scripts to companies and surface per-watcher device-id.
  var byScript = {};
  var debounceTimer = null;
  var DEBOUNCE_MS = 500;

  // --- farble-seed ---
  // Phase 2 Slice 2 step 2: write the per-origin farble contract onto
  // <html> for inject.js's MAIN-world wrappers to read at call-time.
  // Two attributes:
  //   data-wh-farble-state = "off" | "stable" | "per-tab"
  //   data-wh-farble-seed  = 8-char hex int (empty when state="off")
  //
  // Seed = first 4 bytes of HMAC-SHA256(farblerSecret, label) as hex.
  // Labels: "stable|<origin>" or "per-tab|<origin>|<tabNonce>".
  // tabNonce is a placeholder string until per-tab nonce wiring lands.
  //
  // farblerSecret is generated by background.js's onInstalled handler
  // (Slice 2 module 8) and read here. If somehow missing (SW crashed
  // before bootstrap, very rare), we fall back to state="off" rather
  // than generate inline — that path's first-install race leaked ~9
  // canvas calls per fresh install before this module moved the
  // generation up to the SW.
  //
  // Toggle from DevTools service worker console:
  //   chrome.storage.local.set({ farbleDevMode: true })  // turn ON
  //   chrome.storage.local.remove("farbleDevMode")       // turn OFF

  var PER_TAB_NONCE_PLACEHOLDER = "PLACEHOLDER_TABNONCE";

  function bytesToHex(bytes) {
    var hex = "";
    for (var i = 0; i < bytes.length; i++) {
      hex += ("00" + bytes[i].toString(16)).slice(-2);
    }
    return hex;
  }
  function hexToBytes(hex) {
    var bytes = new Uint8Array(hex.length / 2);
    for (var i = 0; i < bytes.length; i++) {
      bytes[i] = parseInt(hex.substr(i * 2, 2), 16);
    }
    return bytes;
  }

  // Returns Uint8Array(64), or null if SW bootstrap hasn't landed yet.
  function getSecret() {
    return new Promise(function (resolve, reject) {
      try {
        chrome.storage.local.get(["farblerSecret"], function (v) {
          if (v && typeof v.farblerSecret === "string" && v.farblerSecret.length === 128) {
            resolve(hexToBytes(v.farblerSecret));
            return;
          }
          DEBUG && console.log("[wh-farble:dw] farblerSecret missing — SW bootstrap not yet landed, skipping farble this load");
          resolve(null);
        });
      } catch (e) { reject(e); }
    });
  }

  // HMAC-SHA256(key, input) → first 4 bytes as 8 hex chars (32-bit seed).
  async function hmacSeed8(keyBytes, input) {
    var keyMat = await crypto.subtle.importKey(
      "raw", keyBytes,
      { name: "HMAC", hash: "SHA-256" },
      false, ["sign"]
    );
    var sig = await crypto.subtle.sign(
      "HMAC", keyMat,
      new TextEncoder().encode(input)
    );
    return bytesToHex(new Uint8Array(sig).slice(0, 4));
  }

  (async function () {
    try {
      var stored = await new Promise(function (resolve) {
        chrome.storage.local.get(["farbleDevMode"], resolve);
      });
      DEBUG && console.log("[wh-farble:dw] storage →", JSON.stringify(stored), "hasDoc=" + !!document.documentElement);
      if (!document.documentElement) return;

      var state = (stored && stored.farbleDevMode) ? "per-tab" : "off";
      var seed = "";
      if (state !== "off") {
        var secret = await getSecret();
        if (!secret) {
          state = "off";  // SW bootstrap not landed; fail safe
        } else {
          var origin = location.hostname || "";
          var label;
          if (state === "stable") {
            label = "stable|" + origin;
          } else { // per-tab
            label = "per-tab|" + origin + "|" + PER_TAB_NONCE_PLACEHOLDER;
          }
          seed = await hmacSeed8(secret, label);
        }
      }
      document.documentElement.setAttribute("data-wh-farble-state", state);
      document.documentElement.setAttribute("data-wh-farble-seed", seed);
      DEBUG && console.log("[wh-farble:dw] set state=" + state + " seed=" + seed);
    } catch (e) {
      DEBUG && console.log("[wh-farble:dw] err:", e && e.message);
    }
  })();
  // --- end farble-seed ---

  // inject.js is loaded by manifest as a MAIN-world content script at
  // document_start (see manifest.json content_scripts). The dynamic
  // <script> injection that used to live here would cause double-wrap of
  // canvas APIs — XOR-based perturbation cancels itself out. Removed.

  // Listen for messages from inject.js
  window.addEventListener("message", function (event) {
    if (event.source !== window) return;
    if (!event.data || event.data.type !== MSG_TYPE) return;

    var api = event.data.api;
    var category = event.data.category;
    var script = event.data.script;

    if (!counts[api]) {
      counts[api] = { category: category, count: 0 };
    }
    counts[api].count++;

    if (script) {
      if (!byScript[script]) byScript[script] = { fingerprint: 0, permission: 0 };
      byScript[script][category] = (byScript[script][category] || 0) + 1;
    }

    scheduleSend();
  });

  function scheduleSend() {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(sendResults, DEBOUNCE_MS);
  }

  function sendResults() {
    var items = [];
    var uniqueFingerprint = 0;
    var uniquePermission = 0;

    var apis = Object.keys(counts);
    for (var i = 0; i < apis.length; i++) {
      var api = apis[i];
      var entry = counts[api];
      items.push({
        api: api,
        category: entry.category,
        count: entry.count
      });
      if (entry.category === "fingerprint") uniqueFingerprint++;
      if (entry.category === "permission") uniquePermission++;
    }

    try {
      chrome.runtime.sendMessage({
        type: "detection",
        module: "watched",
        data: {
          domain: location.hostname,
          items: items,
          byScript: byScript,
          totals: {
            fingerprint: uniqueFingerprint,
            permission: uniquePermission,
            total: uniqueFingerprint + uniquePermission
          }
        }
      });
    } catch (e) { /* service worker not ready */ }
  }
})();
