"use strict";

(function () {
  // Flip to true and reload the extension to surface [wh-farble:dw]
  // diagnostics in the page console. Off by default — these fire at
  // document_start on every navigation and would be noisy in real use.
  var DEBUG = false;

  var MSG_TYPE = "__wearewatched__";
  var counts = {};
  // byScript: { 'google-analytics.com': { fingerprintApis: {api: true},
  //                                       permissionApis: {api: true} }, ... }
  // Track unique APIs per caller-script (not call counts) so background
  // can attribute *surfaces* per company, matching the per-site display.
  // Counting calls let Performance.now()-style polling dominate the
  // per-watcher Blurred column with noise instead of breadth.
  var byScript = {};
  var debounceTimer = null;
  var DEBOUNCE_MS = 500;

  // --- farble-seed ---
  // Phase 2 Slice 2 step 2: write the per-origin farble contract onto
  // <html> for inject.js's MAIN-world wrappers to read at call-time.
  // Two attributes:
  //   data-wh-farble-state = "off" | "stable" | "rotation"
  //   data-wh-farble-seed  = 8-char hex int (empty when state="off")
  //
  // Seed = first 4 bytes of HMAC-SHA256(farblerSecret, label) as hex.
  // Labels:
  //   stable   → "stable|<origin>"            persistent per-origin (pinned)
  //   rotation → "rotation|<salt>|<origin>"   per-origin, rotates with the salt
  // The salt (farblerRotationSalt) is rotated weekly by the SW, so "rotation"
  // gives a per-origin identity that's stable within a window but unlinkable
  // across windows. "stable" omits the salt for sites the user pins (e.g. ones
  // they log into often) where rotation would just cause re-auth friction.
  //
  // farblerSecret is generated by background.js's onInstalled handler
  // (Slice 2 module 8) and read here. If somehow missing (SW crashed
  // before bootstrap, very rare), we fall back to state="off" rather
  // than generate inline — that path's first-install race leaked ~9
  // canvas calls per fresh install before this module moved the
  // generation up to the SW. The rotation salt is treated the same way:
  // absent → fall back to "off" for that load.
  //
  // Default blur mode is set from the dashboard Settings radio:
  //   chrome.storage.local.defaultBlurMode = "off" | "stable" | "rotation"
  // Defaults to "rotation" when unset. Per-site overrides in farblerSettings
  // win over the default. Legacy "per-tab" (an unwired stub) maps to "rotation".

  function bytesToHex(bytes) {
    var hex = "";
    for (var i = 0; i < bytes.length; i++) {
      hex += ("00" + bytes[i].toString(16)).slice(-2);
    }
    return hex;
  }
  function hexToBytes(hex) {
    var bytes = new Uint8Array(hex.length / 2);
    for (var i = 0; i < bytes.length; i++) {
      bytes[i] = parseInt(hex.substr(i * 2, 2), 16);
    }
    return bytes;
  }

  // Returns Uint8Array(64), or null if SW bootstrap hasn't landed yet.
  function getSecret() {
    return new Promise(function (resolve, reject) {
      try {
        chrome.storage.local.get(["farblerSecret"], function (v) {
          if (v && typeof v.farblerSecret === "string" && v.farblerSecret.length === 128) {
            resolve(hexToBytes(v.farblerSecret));
            return;
          }
          DEBUG && console.log("[wh-farble:dw] farblerSecret missing — SW bootstrap not yet landed, skipping farble this load");
          resolve(null);
        });
      } catch (e) { reject(e); }
    });
  }

  // HMAC-SHA256(key, input) → first 4 bytes as 8 hex chars (32-bit seed).
  async function hmacSeed8(keyBytes, input) {
    var keyMat = await crypto.subtle.importKey(
      "raw", keyBytes,
      { name: "HMAC", hash: "SHA-256" },
      false, ["sign"]
    );
    var sig = await crypto.subtle.sign(
      "HMAC", keyMat,
      new TextEncoder().encode(input)
    );
    return bytesToHex(new Uint8Array(sig).slice(0, 4));
  }

  // Match the popup's etld1 derivation (last two labels) for per-site
  // override lookup. Crude but matches the existing scoper convention.
  // Keep in sync with background.js `harvestEtld1` — the relax-offer key is
  // written there and read here, so they must agree.
  function etld1FromHost(host) {
    if (!host) return "";
    var labels = String(host).split(".").filter(Boolean);
    if (labels.length < 2) return host;
    return labels.slice(-2).join(".");
  }

  (async function () {
    try {
      var stored = await new Promise(function (resolve) {
        chrome.storage.local.get(["defaultBlurMode", "farblerSettings", "farbleDisableFamilies", "farblerRotationSalt"], resolve);
      });
      DEBUG && console.log("[wh-farble:dw] storage →", JSON.stringify(stored), "hasDoc=" + !!document.documentElement);
      if (!document.documentElement) return;

      var origin = location.hostname || "";
      var etld1 = etld1FromHost(origin);
      var settings = (stored && stored.farblerSettings) || {};
      var override = settings[etld1] || null;
      // Legacy "per-tab" (an unwired stub that behaved like a second stable
      // mode) folds into "rotation" so old stored defaults/overrides resolve.
      var normMode = function (m) { return m === "per-tab" ? "rotation" : m; };
      var defaultMode = normMode((stored && stored.defaultBlurMode) || "rotation");

      // Per-origin override wins over the default, unconditionally. Modes:
      //   "off"      → blur disabled here (user trusted ID)
      //   "stable"   → persistent per-origin seed (pinned, no rotation)
      //   "rotation" → per-origin seed salted with the weekly rotation salt
      var omode = override ? normMode(override.mode) : null;
      var state;
      if (omode === "off") {
        state = "off";
      } else if (omode === "stable") {
        state = "stable";
      } else if (omode === "rotation") {
        state = "rotation";
      } else if (defaultMode === "off") {
        state = "off";
      } else if (defaultMode === "stable") {
        state = "stable";
      } else {
        state = "rotation";
      }

      var seed = "";
      if (state !== "off") {
        var secret = await getSecret();
        if (!secret) {
          state = "off";  // SW bootstrap not landed; fail safe
        } else if (state === "stable") {
          seed = await hmacSeed8(secret, "stable|" + origin);
        } else { // rotation
          var salt = stored && stored.farblerRotationSalt;
          if (typeof salt !== "string" || !salt) {
            state = "off";  // salt not seeded yet; fail safe rather than use a constant label
          } else {
            seed = await hmacSeed8(secret, "rotation|" + salt + "|" + origin);
          }
        }
      }
      document.documentElement.setAttribute("data-wh-farble-state", state);
      document.documentElement.setAttribute("data-wh-farble-seed", seed);
      // Per-family disable (diagnostic / per-site relax). Global list for now:
      //   chrome.storage.local.set({ farbleDisableFamilies: ["webgl"] })
      // inject.js skips farbling for any listed family (canvas|webgl|audio|
      // fonts|screennav). Empty/absent → all families follow the state above.
      var disable = (stored && stored.farbleDisableFamilies);
      var disableStr = Array.isArray(disable) ? disable.join(",") : (typeof disable === "string" ? disable : "");
      if (disableStr) document.documentElement.setAttribute("data-wh-farble-disable", disableStr);
      else document.documentElement.removeAttribute("data-wh-farble-disable");
      DEBUG && console.log("[wh-farble:dw] set state=" + state + " seed=" + seed + (override ? " (override=" + override.mode + ")" : "") + (disableStr ? " disable=" + disableStr : ""));
    } catch (e) {
      DEBUG && console.log("[wh-farble:dw] err:", e && e.message);
    }
  })();
  // --- end farble-seed ---

  // --- relax banner (in-page) ------------------------------------------
  // background.js flags farbleReloadOffer[etld1] when a user rage-reloads a
  // site that's likely broken by fingerprint blur. Show a top banner offering
  // one-click relax + reload — far more discoverable than expecting the user
  // to find our toolbar popup. Top frame + http(s) only. Rendered in a shadow
  // root with styles set via the CSSOM (not a <style> tag / style attribute),
  // so the page's CSS can't distort it and a strict CSP can't block it. We
  // react to storage.onChanged so it appears on the current load, and also
  // check once at start in case the flag predates this load.
  var WH_RELAX_ETLD1 = (function () { try { return etld1FromHost(location.hostname || ""); } catch (e) { return ""; } })();
  var whRelaxShown = false;

  function showRelaxBanner(etld1) {
    if (whRelaxShown || window.top !== window || !document.documentElement) return;
    if (document.getElementById("wh-relax-banner-host")) return;
    whRelaxShown = true;

    var hostEl = document.createElement("div");
    hostEl.id = "wh-relax-banner-host";
    hostEl.style.cssText = "position:fixed;top:0;left:0;right:0;z-index:2147483647;";
    var root = hostEl.attachShadow ? hostEl.attachShadow({ mode: "open" }) : hostEl;

    var bar = document.createElement("div");
    bar.style.cssText = "display:flex;align-items:center;justify-content:center;gap:10px;" +
      "position:relative;padding:10px 44px;" +
      "background:#1a1b26;color:#c0caf5;border-bottom:2px solid #e0af68;" +
      "font:13px/1.4 'JetBrains Mono','IBM Plex Mono',ui-monospace,Menlo,monospace;" +
      "box-shadow:0 2px 8px rgba(0,0,0,0.4);";

    // Full [we]arehere wordmark, matching the popup.
    var brand = document.createElement("span");
    brand.style.cssText = "flex-shrink:0;font-weight:800;";
    var we = document.createElement("span"); we.textContent = "[we]"; we.style.cssText = "color:#e0af68;";
    var rest = document.createElement("span"); rest.textContent = "arehere"; rest.style.cssText = "color:#c0caf5;";
    brand.appendChild(we); brand.appendChild(rest);

    var msg = document.createElement("span");
    msg.textContent = etld1 + " may not work with fingerprint protection on.";
    msg.style.cssText = "min-width:0;";

    var relax = document.createElement("button");
    relax.textContent = "relax & reload";
    relax.style.cssText = "flex-shrink:0;cursor:pointer;padding:5px 12px;border:1px solid #e0af68;" +
      "background:#e0af68;color:#1a1b26;font:inherit;font-weight:700;border-radius:3px;";

    var close = document.createElement("button");
    close.textContent = "✕";
    close.setAttribute("aria-label", "dismiss");
    close.style.cssText = "position:absolute;right:10px;top:50%;transform:translateY(-50%);" +
      "cursor:pointer;padding:5px 9px;border:1px solid #565f89;" +
      "background:transparent;color:#9aa5ce;font:inherit;border-radius:3px;";

    relax.addEventListener("click", function () {
      DEBUG && console.log("[wh-farble:relax] relax clicked for " + etld1);
      // Dismiss synchronously — instant feedback and not gated on any async
      // callback (the previous bug: reload was the callback to a storage write
      // that never fired once this page's content-script context was torn down
      // by the anti-bot script right after the banner appeared).
      try { hostEl.remove(); } catch (e) {}
      var reloaded = false;
      var doReload = function () {
        if (reloaded) return; reloaded = true;
        try { location.reload(); } catch (e) { try { location.href = location.href; } catch (e2) {} }
      };
      // Persist blur-off + reload via the service worker. Its context is stable
      // (unlike this page's, which the site can tear down) and chrome.tabs.reload
      // doesn't depend on page JS surviving. Only reload page-side when the SW is
      // unreachable (context already dead); otherwise trust the SW reload and keep
      // a long backstop in case it never lands. A fresh content script re-shows
      // the still-pending offer if we reload before the relax could persist.
      try {
        if (chrome.runtime && chrome.runtime.id) {
          chrome.runtime.sendMessage({ type: "wh-relax-site", etld1: etld1 }, function () {
            void (chrome.runtime && chrome.runtime.lastError);
          });
          setTimeout(doReload, 3000);  // backstop only; the SW reload wins normally
        } else {
          doReload();                  // ctx dead — SW unreachable, reload now
        }
      } catch (e) { doReload(); }
    });
    close.addEventListener("click", function () {
      try { hostEl.remove(); } catch (e) {}
      // Clear via the SW for the same reason relax does — this page's context may
      // already be torn down, so a page-side storage write could silently no-op.
      try {
        if (chrome.runtime && chrome.runtime.id) {
          chrome.runtime.sendMessage({ type: "wh-clear-relax-offer", etld1: etld1 }, function () {
            void (chrome.runtime && chrome.runtime.lastError);
          });
        }
      } catch (e) {}
    });

    bar.appendChild(brand); bar.appendChild(msg); bar.appendChild(relax); bar.appendChild(close);
    root.appendChild(bar);
    document.documentElement.appendChild(hostEl);
    DEBUG && console.log("[wh-farble:relax] banner shown for " + etld1);
  }

  function whCheckRelaxOffer() {
    if (window.top !== window || !/^https?:$/.test(location.protocol) || !WH_RELAX_ETLD1) return;
    chrome.storage.local.get("farbleReloadOffer", function (s) {
      var o = s && s.farbleReloadOffer && s.farbleReloadOffer[WH_RELAX_ETLD1];
      if (o && o.at && (Date.now() - o.at) < 10 * 60 * 1000) showRelaxBanner(WH_RELAX_ETLD1);
    });
  }

  chrome.storage.onChanged.addListener(function (changes, area) {
    if (area === "local" && changes.farbleReloadOffer) whCheckRelaxOffer();
  });
  whCheckRelaxOffer();
  // --- end relax banner ------------------------------------------------


  // inject.js is loaded by manifest as a MAIN-world content script at
  // document_start (see manifest.json content_scripts). The dynamic
  // <script> injection that used to live here would cause double-wrap of
  // canvas APIs — XOR-based perturbation cancels itself out. Removed.

  // Listen for messages from inject.js
  window.addEventListener("message", function (event) {
    if (event.source !== window) return;
    if (!event.data || event.data.type !== MSG_TYPE) return;

    var api = event.data.api;
    var category = event.data.category;
    var script = event.data.script;

    if (!counts[api]) {
      counts[api] = { category: category, count: 0 };
    }
    counts[api].count++;

    if (script) {
      if (!byScript[script]) byScript[script] = { fingerprintApis: {}, permissionApis: {} };
      var bucket = category === "fingerprint" ? byScript[script].fingerprintApis
                 : category === "permission"  ? byScript[script].permissionApis
                 : null;
      if (bucket) bucket[api] = true;
    }

    scheduleSend();
  });

  function scheduleSend() {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(sendResults, DEBOUNCE_MS);
  }

  function sendResults() {
    var items = [];
    var uniqueFingerprint = 0;
    var uniquePermission = 0;

    var apis = Object.keys(counts);
    for (var i = 0; i < apis.length; i++) {
      var api = apis[i];
      var entry = counts[api];
      items.push({
        api: api,
        category: entry.category,
        count: entry.count
      });
      if (entry.category === "fingerprint") uniqueFingerprint++;
      if (entry.category === "permission") uniquePermission++;
    }

    var byScriptFlat = {};
    var scripts = Object.keys(byScript);
    for (var s = 0; s < scripts.length; s++) {
      var sh = scripts[s];
      byScriptFlat[sh] = {
        fingerprint: Object.keys(byScript[sh].fingerprintApis).length,
        permission:  Object.keys(byScript[sh].permissionApis).length
      };
    }

    try {
      chrome.runtime.sendMessage({
        type: "detection",
        module: "watched",
        data: {
          domain: location.hostname,
          items: items,
          byScript: byScriptFlat,
          totals: {
            fingerprint: uniqueFingerprint,
            permission: uniquePermission,
            total: uniqueFingerprint + uniquePermission
          }
        }
      });
    } catch (e) { /* service worker not ready */ }
  }
})();
